server:
  port: 8090
  servlet:
    context-path: /
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
# 添加热部署的配置
  devtools:
    restart:
      # 启用热部署
      enabled: true
      # 需要进行热部署的目录
      additional-paths: src/main/java
      # 文件修改时不需要热部署的目录
      exclude: src/main/resources/static

mybatis-plus:
  type-aliases-package: com.jiuqiyou.jqyitemcommon.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.jiuqiyou.jqyitemmanage.mapper: debug

